### ISSUE TITLE
local variable 'net' referenced before assignment

### ISSUE THREAD

**Issue by HuaYanGuan** [jqyang22/HSIC-FM#1]
File "/content/gdrive/MyDrive/research/main.py", line 186, in <module>
    net = FullModel(
  File "/content/gdrive/MyDrive/research/HSIC_FM.py", line 180, in __init__
    self.recurrent = net(input_size, args.d, args.depth)
UnboundLocalError: local variable 'net' referenced before assignment

**Comment by jqyang22** [comment]
> File "/content/gdrive/MyDrive/research/main.py", line 186, in net = FullModel( File "/content/gdrive/MyDrive/research/HSIC_FM.py", line 180, in **init** self.recurrent = net(input_size, args.d, args.depth) UnboundLocalError: local variable 'net' referenced before assignment

Hello, please run:
python ./main.py --lstm
"--lstm" is used to choose the lstm net for subsequent processing.

**Comment by HuaYanGuan** [comment]
Thank you very much. It works.

> > File "/content/gdrive/MyDrive/research/main.py", line 186, in net = FullModel( File "/content/gdrive/MyDrive/research/HSIC_FM.py", line 180, in **init** self.recurrent = net(input_size, args.d, args.depth) UnboundLocalError: local variable 'net' referenced before assignment
> 
> Hello, please run: python ./main.py --lstm "--lstm" is used to choose the lstm net for subsequent processing.

Thank you very much, it works
